### ISSUE TITLE
/glossary

### ISSUE THREAD

**Issue by deadlyicon** [LearnersGuild/curriculum-app#300]
# `/glossary` feature

## User Stories

- As a user when I visit `/glossary` 
  - I can see a list of terms commonly used in web development
  - I can click on a word and be taken to `/glossary/:termSlug` 
- As a user when I visit `/glossary/:termSlug` 
  - I can see a definition of the term
  - I can see links to resources for said term
- As a user when I am reading any page within the curriculum 
  - terms in the glossary are double-underlined 
  - when I hover over a term in the glossary
    - that terms definition is hovered along side mouse piinter
    - I can click a link to open that terms definition page

## Technical Notes

- add a `/glossary` folder to the repo
- add a `/bin/add-term` script
- add `digest.glossary` and suck in all the terms and their markdown file paths

### `/bin/add-term` script

This script should be used to add terms to our repository. It should generate a consistently formatted markdown file. 

```sh
$ add-term "join table"
``` 

should create `/glossary/join-table.md` prepopulated with text like this:

```markdown
# Join table

## Definition

_definition goes here_

## References

- _links go here_

### Reading

- _links go here_

### Watching

```

### `digest.glossary`

```js

digest.glossary = {
  "join-table": {
    id: "join-table",
    value: "Join table",
    markdownFilePath: "/glossary/join-table.md",
    definitionHTML: "<extracted from markdown file>",
    definitionText: "<extracted from markdown file and stripped of html>",
  },
  "array": {
    id: "array",
    value: "array",
    markdownFilePath: "/glossary/array.md",
    definitionHTML: "<extracted from markdown file>",
    definitionText: "<extracted from markdown file and stripped of html>",
  }
}

**Comment by hhhhhaaaa** [comment]
Plan of Action
1.) Create digest.glossary through glossary.js file.
a.) Look through other digest js files, gather information needed.
b.) Create glossary.js file. (Write the code necessary to introduce the glossary into digest.)
c.) Call glossary through digest/index.

2.) Create routes/views needed for glossary.
a.) Create glossary and glossary/:termSlug routes.
b.) Create glossary views for both routes.
c.) Create glossary styling for both view.

3.) Create add-term script.
a.) Script adds term to digest.
b.) Script adds .md file for term to /glossary folder.

4.) Populate glossary.
a.) Add a good number of terms to the glossary.
b.) Update terms with necessary information.

5.) Figure out how to add glossary links/styling to.

**Comment by zubairnahmed** [comment]
Here's the PR: https://github.com/LearnersGuild/curriculum/pull/329

**Comment by hhhhhaaaa** [comment]
Here's the PR: #335

**Comment by hhhhhaaaa** [comment]
Here's the PR: #339

**Comment by hhhhhaaaa** [comment]
Here's the PR: #358

**Comment by hhhhhaaaa** [comment]
Here's the PR: #373

**Comment by hhhhhaaaa** [comment]
Here's the PR: #378
