### ISSUE TITLE
Write tests for routes: calendar, guide

### ISSUE THREAD

**Issue by deadlyicon** [LearnersGuild/curriculum-app#318]
We have a serious lack of http request specs for our web application. We need to ensure the route we've written work as expected. 

Write tests for 
- `web-server/routes/calendar.js` in `web-server/routes/calendar.test.js`
- `web-server/routes/guide.js` in `web-server/routes/guide.test.js`

## Tips

- See the tests in `web-server/routes/goals.test.js` for a pattern guide. 
- If the routes your testing respond with HTML, we might need to find and install a new dependency to help us make assertions about html. Something like `chai-html`
- If your route makes database or api calls we might need to use `sinon` to stub some methods to return some mock objects.

**Comment by optomal7** [comment]
Please assign myself and jrpool to this ticket.

**Comment by optomal7** [comment]
#354

**Comment by optomal7** [comment]
#372

**Comment by optomal7** [comment]
#379
