### ISSUE TITLE
Write tests for routes: profile, users

### ISSUE THREAD

**Issue by deadlyicon** [LearnersGuild/curriculum-app#320]
We have a serious lack of http request specs for our web application. We need to ensure the route we've written work as expected. 

Write tests for 
- `web-server/routes/profile.js` in `web-server/routes/profile.test.js`
- `web-server/routes/users.js` in `web-server/routes/users.test.js`

## Tips

- See the tests in `web-server/routes/goals.test.js` for a pattern guide. 
- If the routes your testing respond with HTML, we might need to find and install a new dependency to help us make assertions about html. Something like `chai-html`
- If your route makes database or api calls we might need to use `sinon` to stub some methods to return some mock objects.

**Comment by optomal7** [comment]
Im trying to work on this. Lo and behold /profile and /users produces errors when process.env.DISABLE_IDM = '1'
