### ISSUE TITLE
Write tests for routes: digest, phases, modules, skills, cos

### ISSUE THREAD

**Issue by deadlyicon** [LearnersGuild/curriculum-app#321]
We have a serious lack of http request specs for our web application. We need to ensure the route we've written work as expected. 

Write tests for 
- `web-server/routes/digest.js` in `web-server/routes/digest.test.js`
- `web-server/routes/phases.js` in `web-server/routes/phases.test.js`
- `web-server/routes/modules.js` in `web-server/routes/modules.test.js`
- `web-server/routes/skills.js` in `web-server/routes/skills.test.js`
- `web-server/routes/cos.js` in `web-server/routes/cos.test.js`

## Tips

- See the tests in `web-server/routes/goals.test.js` for a pattern guide. 
- If the routes your testing respond with HTML, we might need to find and install a new dependency to help us make assertions about html. Something like `chai-html`
- If your route makes database or api calls we might need to use `sinon` to stub some methods to return some mock objects.

**Comment by aaronev** [comment]
PR: #367

NOTES: Unable to write test for routes/modules, routes/skills, routes/phases/:phaseNumber/dashboard, routes/phases/:phaseNumber/skills
due to access issues

**Comment by aaronev** [comment]
PR: #380
